theme              : jekyll-theme-cayman
title              : Classroom Resources Manager
description        : >-
                    This website serves as a template for teachers that want to generate
                    a website to provide resources by course to their students.

url                : http://jsanz.github.io/classroom-resources
baseurl            : /classroom-resources

# SEO tag
twitter:
  username         : xurxosanz

author:
  name             : xurxosanz
  email            : xurxosanz@gmail.com

social:
  name             : Jorge Sanz
  links:
                   - https://twitter.com/xurxosanz
                   - https://www.linkedin.com/in/jsanz
                   - https://github.com/jsanz
                   - https://keybase.io/jsanz

plugins:
  - jekyll-seo-tag

# Build settings
highlighter        : rouge
markdown           : kramdown
lsi                : false

collections:
  courses:
    output        : true
    permalink     : /:collection/:title 
  resources:
    output        : true
    permalink     : /:collection/:title

defaults:
  - scope:
      path         : ""
      type         : courses
    values:
      layout       : course
  - scope:
      path         : ""
      type         : resources
    values:
      type         : pdf
      date         : 2017-12-01 00:00:00
      layout       : resource

include:
                   - _pages

exclude: 
                   - LICENSE
                   - README.md
                   - CNAME
                   - .gitignore
                   - Gemfile
                   - Gemfile.lock
                   - .jekyll-metadata

